### TOPIC SEND
POST http://localhost:8080/api/topic/enviar
Content-Type: application/json

"{{$datetime iso8601}} walter "

### TOPIC SEND
POST http://localhost:8080/api/queue/enviar
Content-Type: application/json

"{{$datetime iso8601}} walter "

### RECEIVE
GET http://localhost:8080/api/receber
Content-Type: application/json




